# Generated by Django 5.2.4 on 2025-07-31 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('in_out', models.IntegerField(choices=[(0, '来た'), (1, '行くつもり'), (2, '行かない'), (3, '未登録')], default=3, verbose_name='IN/OUT')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='名前')),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
