# Generated by Django 5.2.4 on 2025-08-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='今日のコメント'),
        ),
    ]
